### Ir a la pagina principal
http://localhost:3000

### Mostrar todos los productos
GET http://localhost:3000/electronicos

### Mostrar los productos de una categoria
GET http://localhost:3000/electronicos/categorias/Hogar

### Mostrar un producto por id
GET http://localhost:3000/electronicos/6679dba4bdcfc3e1a47a9472


### Crear un producto
POST http://localhost:3000/electronicos/
Content-Type: application/json

{
    "codigo": 58,
    "nombre": "Telefono",
    "precio": 3060,
    "categorias": "Electronica"
}

### Actualizar un producto parcialmente
PATCH  http://localhost:3000/electronicos/667dc1dd77b70f342b0759aa
content-type: application/json

{
    "precio": 20000
}

### Actualizar un producto totalmente
PUT http://localhost:3000/electronicos/667dc1dd77b70f342b0759aa
content-type: application/json

{
    "codigo": "60",
    "nombre": "Tablet SD87",
    "precio": 300000,
    "categorias": "Tablet"
}

### Borrar un producto  
DELETE http://localhost:3000/electronicos/6688621eeefa83b6ecfec266

### Mostrar producto por nombre especifico
GET http://localhost:3000/electronicos/nombre/Router WiFi

### Mostrar producto por codigo especifico
GET http://localhost:3000/electronicos/codigo/27

### Mostrar producto con precio mayor al especificado
GET http://localhost:3000/electronicos/precio/mayor/300

### Mostrar productos con importe menor al especificado
GET http://localhost:3000/electronicos/precio/menor/300
